### ISSUE TITLE
[Dev-1.x] MMCV2.0 & Apple Silicon failed to deploy due to PyTorch-Nightly

### ISSUE THREAD

**Issue by xin-li-67** [open-mmlab/mmdeploy#1134] opened 2022-09-29 05:56 UTC
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Due to the fact that **mmcv>=2.0.0rc** requires **Pytorch-Nightly** on apple silicon devices, I came across some problems that are all related to this nightly version of PyTorch.

Seems like in the nightly version (or the future version) of PyTorch, some features, such as `from torch.onnx.symbolic_registry import XXX` and `torch.distributed' has no attribute 'ReduceOp'` ,will be rewritten or changed. 

### Reproduction

1. What command or script did you run?
    I tried with **deploy.py** and **check_env.py**, and they all have this issue.
3. Did you make any modifications on the code or config? Did you understand what you have modified? 
    No, just vanilla build from the **dev-1.x* branch.

### Environment

```Shell
Sorry for `python tools/check_env.py` failing in this version of PyTorch.

2.1 How you installed PyTorch:
    I first use `conda install pytorch torchvision -c pytorch-nightly` to install pytorch, then I build the libtorch from source.
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "mmdeploy/tools/deploy.py", line 12, in <module>
    from mmdeploy.apis import (create_calib_input_data, extract_model,
  File "/Users/xinli/Study/Projects/MM2.0/mmdeploy/mmdeploy/__init__.py", line 8, in <module>
    importlib.import_module('mmdeploy.pytorch')
  File "/Users/xinli/opt/anaconda3/envs/mmdev/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/xinli/Study/Projects/MM2.0/mmdeploy/mmdeploy/pytorch/__init__.py", line 2, in <module>
    from .functions import *  # noqa: F401,F403
  File "/Users/xinli/Study/Projects/MM2.0/mmdeploy/mmdeploy/pytorch/functions/__init__.py", line 2, in <module>
    from .adaptive_pool import (adaptive_avg_pool2d__default,
  File "/Users/xinli/Study/Projects/MM2.0/mmdeploy/mmdeploy/pytorch/functions/adaptive_pool.py", line 6, in <module>
    from mmdeploy.core import FUNCTION_REWRITER
  File "/Users/xinli/Study/Projects/MM2.0/mmdeploy/mmdeploy/core/__init__.py", line 2, in <module>
    from .optimizers import *  # noqa: F401,F403
  File "/Users/xinli/Study/Projects/MM2.0/mmdeploy/mmdeploy/core/optimizers/__init__.py", line 3, in <module>
    from .function_marker import mark, reset_mark_function_count
  File "/Users/xinli/Study/Projects/MM2.0/mmdeploy/mmdeploy/core/optimizers/function_marker.py", line 7, in <module>
    from mmdeploy.core.rewriters import FUNCTION_REWRITER
  File "/Users/xinli/Study/Projects/MM2.0/mmdeploy/mmdeploy/core/rewriters/__init__.py", line 2, in <module>
    from .rewriter_manager import (FUNCTION_REWRITER, MODULE_REWRITER,
  File "/Users/xinli/Study/Projects/MM2.0/mmdeploy/mmdeploy/core/rewriters/rewriter_manager.py", line 11, in <module>
    from .symbolic_rewriter import SymbolicRewriter
  File "/Users/xinli/Study/Projects/MM2.0/mmdeploy/mmdeploy/core/rewriters/symbolic_rewriter.py", line 6, in <module>
    from torch.onnx.symbolic_registry import _registry as pytorch_registry
ModuleNotFoundError: No module named 'torch.onnx.symbolic_registry'
```

**Comment by grimoire** [comment] 2022-09-29 06:00
This might be caused by https://github.com/open-mmlab/mmcv/issues/2279. We are trying to fix it in master branch https://github.com/open-mmlab/mmdeploy/pull/1122/files. It will be fixed in dev-1.x soon.

**Comment by xin-li-67** [comment] 2022-09-29 06:25
> This might be caused by [open-mmlab/mmcv#2279](https://github.com/open-mmlab/mmcv/issues/2279). We are trying to fix it in master branch https://github.com/open-mmlab/mmdeploy/pull/1122/files. It will be fixed in dev-1.x soon.

Glad to hear that~

**Closed** 2022-12-23 01:50 UTC
