### ISSUE TITLE
MMDeploy build failed on Windows platform with only `mmdet` enabled in MMDEPLOY_CODEBASES option// hello,编译报错，如图

### ISSUE THREAD

**Issue by dgl547437235** [open-mmlab/mmdeploy#734] opened 2022-07-11 15:32 UTC
![image](https://user-images.githubusercontent.com/31400928/178301130-10c6e8c7-65c1-4f24-a8e4-5671d8ec88b9.png)

**Comment by dgl547437235** [comment] 2022-07-11 15:33
你好，所有编译项中只有mmdet没有编译通过，是我的源码版本不对吗

**Comment by irexyc** [comment] 2022-07-12 02:56
What is your git commit id? And how you configure the project?

**Comment by irexyc** [comment] 2022-07-13 06:32
I can't reproduce the problem. Can you try to build with -DMMDEPLOY_CODEBASES="mmcls" other than "all" to check if it can compile success.

**Comment by dgl547437235** [comment] 2022-07-13 06:58
yes ,all but 'mmdet' are all ok

**Comment by lvhan028** [comment] 2022-07-14 02:34
Hi, @dgl547437235 
MMDeploy build with onnxruntime as an inference backend on Windows platform has been added to CircleCI. 
You can refer to https://github.com/open-mmlab/mmdeploy/blob/dace58e844905cbd18c9f5b0490960119318c2e4/.circleci/test.yml#L205

When a PR is merged to master, the build workflow is invoked by CircleCI, the result can be found in the PR checks section, e.g., 
<img width="212" alt="1657765753723" src="https://user-images.githubusercontent.com/4560679/178885187-294dafb7-1f35-4fc2-a4ec-9660a04c88cb.png">

**Comment by lvhan028** [comment] 2022-08-05 02:46
Closing it since no activity for a long time. Feel free to reopen it if it is still an issue

**Closed by lvhan028** 2022-08-05 02:46 UTC
Labels: Windows, SDK
