### ISSUE TITLE
High memory usage during inference

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [open-mmlab/mmdeploy#308] opened 2022-04-03 05:34 UTC
I am using HRNet_w32 pretrained model for my project. The size of the pretrained model is around 110 MB. But when I load the model (with init_detector()), The memory consumption was much higher (More than 1GB - GPU + CPU memory). What is the reason for this unexpected behaviour? How can I reduce the memory consumption of model loading..

Note : I am using Jetson nano. Model is running in GPU.

Thank you

**Comment by AllentDan** [comment] 2022-04-04 07:37
What backend did you use? And I don't think the model file should be the same size as the memory consumption after it got loaded into codes.

**Comment by shameem198** [comment] 2022-04-04 08:58
Faced memory leak in Linux-x86_64 detection inference using onnxruntime as backend

**Comment by AllentDan** [comment] 2022-04-06 06:20
Close this as it is a duplicate of issue [309](https://github.com/open-mmlab/mmdeploy/issues/309).

**Closed by AllentDan** 2022-04-06 06:20 UTC
